# ---------------------------------------------------------------
# Jekyll & Global Configuration
## Docs: https://jekyllrb.com/docs/configuration/
# ---------------------------------------------------------------

# Site
title: Tony Klin's Notes
subtitle:
description:
author: Tony Klinakis
repository: aklin/aklin.github.io
language: en
date_format: '%Y-%m-%d'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com' and baseurl as '/child'
url:
baseurl:
permalink: pretty

# Pagination
paginate: 12
#paginate_path: "/page:num/"
#archive:
  #paginate: 10
  #paginate_path: "/page:num/"
#category:
  #paginate: 10
  #paginate_path: "/page:num/"
#tag:
  #paginate: 10
  #paginate_path: "/page:num/"

# Handling Reading
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "README_en.md"]

# Separator
#excerpt_separator: <!-- more -->

# Code Highlighter
## 'pygments' is unsupported on GitHub Pages now.
highlighter: rouge

#### Markdown Processors
## 'redcarpet' is unsupported on GitHub Pages now.
markdown: kramdown
kramdown:
    input: GFM

# Default Attributes
## Docs: https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

# Atom feed
feed:
  path: atom.xml

# Plugins
## Docs: https://help.github.com/articles/configuring-jekyll-plugins/
plugins:
# jemoji conficts with toc in some no-ascii post
# - jemoji
 - jekyll-sitemap
 - jekyll-feed
 - jekyll-extlinks


# Extlinks config: https://github.com/d-ogarkov/jekyll-extlinks

extlinks:
  attributes: {rel: nofollow, target: _blank}
#  rel_exclude: ['host1.com', 'host2.net']

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Put your favicon.ico into `assets/` directory.
favicon: /assets/favicon.ico

# Set default keywords (Use a comma to separate)
keywords: "Jekyll, NexT"

# Set rss to false to disable feed link.
# Leave rss as empty to use site's feed link.
# Set rss to specific value if you have burned your feed already.
rss:

# Specify the date when the site was setup
since: 2017

# Creative Commons 4.0 International License.
# http://creativecommons.org/
# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons: by

# Blog rolls
#links_title: Links
#links_layout: block
#links_layout: inline
#links:
  #Title: http://example.com/

# ---------------------------------------------------------------
# Post Settings
# ---------------------------------------------------------------

# Declare license on posts
post_copyright:
  enable: false
  license: CC BY-NC-SA 3.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/


# Code Highlight theme
# Available value:
#    normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: "normal"

# Show Calendly widget in these pages
contact_widget:
  global: false
  cv: true
  contact: false

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification: YQlekIb1KSnelFo56vD4eNQ2Q0N0x1ca3SyyXPOMI6I

# Google Analytics
google_analytics: UA-113086665-1

